### ISSUE TITLE
BUG: Cannot read properties of undefined (reading 'width')

### ISSUE THREAD

**Issue by kmkaliraj** [GrapesJS/grapesjs#5386]
### GrapesJS version

- [X] I confirm to use the latest version of GrapesJS

### What browser are you using?

Edge

### Reproducible demo link

NA

### Describe the bug

**How to reproduce the bug?**
Version: 0.18.2
We have the following error logged in our system from grapejs module. We are not sure in which scenario this error is thrown.
TypeError: Cannot read properties of undefined (reading 'width')
    at Object.getTargetToElementFixed (https://content.domain.com/resource/makerx/static/js/module/vendors~form-designer~c7cc6222.85501132.chunk.js:2:6330393)
    at i.updateToolsGlobal (https://content.domain.com/resource/makerx/static/js/module/vendors~form-designer~c7cc6222.85501132.chunk.js:2:5923375)
    at i.updateGlobalPos (https://content.domain.com/resource/makerx/static/js/module/vendors~form-designer~c7cc6222.85501132.chunk.js:2:5917048)
    at i.onFrameUpdated (https://content.domain.com/resource/makerx/static/js/module/vendors~form-designer~c7cc6222.85501132.chunk.js:2:5916217)
    at $e (https://content.domain.com/resource/makerx/static/js/module/vendors~form-designer~c7cc6222.85501132.chunk.js:2:5648540)

**What is the expected behavior?**
..

**What is the current behavior?**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by artf** [comment]
0.18.2 it's quite an old version, you have to upgrade
